# GNU Makefile for neuroconda. Commands:
# install (default target): create a new environment from neuroconda.yml
# install-cbu: install and copy over CBU-specific env_vars.{sh,csh} scripts to add
# 	support for non-conda packages (freesurfer, ants, etc).
# update: create a new neuroconda.yml by building an environment from
# 	neuroconda_basepackages.yml and exporting.
# clean-update, clean-install: remove environments generated by update and install.
SHELL := /bin/bash
# make sure bash exceptions propagate to make
.SHELLFLAGS = -ec
NEUROCONDA_VERSION = neuroconda_1_5

# TODO
# handle overwrite Dcm2bids github install (currently the only one).

# TODO - test make install
# default to first environment directory (tends to be user in centralized installs)
PREFIX ?= $(shell echo `conda info | grep "envs directories" | cut -d ":" -f 2`/)

install: clean-install
	{ \
	source $(conda info --base)/etc/profile.d/conda.sh ;\
	conda env create -f neuroconda.yml --prefix $(PREFIX)$(NEUROCONDA_VERSION) ;\
	conda activate $(PREFIX)$(NEUROCONDA_VERSION) ;\
	python -c "import cortex" ;\
	sed -i \
	's@build/bdist.linux-x86_64/wheel/pycortex-1.0.2.data/data@'$(CONDA_PREFIX)'@g' \
	~/.config/pycortex/options.cfg ;\
	jupyter serverextension enable --py jupyterlab_code_formatter ;\
	echo "neuroconda install completed at $(PREFIX)$(NEUROCONDA_VERSION)." ;\
	}

install-cbu: install
	{ \
	source $(conda info --base)/etc/profile.d/conda.sh ;\
	conda activate $(PREFIX)$(NEUROCONDA_VERSION) ;\
	rsync -rv --exclude '*.swp' etc/ $(CONDA_PREFIX)/etc/ ;\
	echo "neuroconda cbu-install completed at $(PREFIX)$(NEUROCONDA_VERSION)." ;\
	}

update: clean-update
	{ \
	source $(conda info --base)/etc/profile.d/conda.sh ;\
	conda env create -f neuroconda_basepackages.yml --prefix $(PREFIX)neuroconda_build ;\
	conda env export --prefix $(PREFIX)neuroconda_build -f neuroconda.yml --no-builds ;\
	echo "neuroconda update completed, neuroconda.yml generated." ;\
	echo "**MANUAL EDITS TO DCM2BIDS PIP ENTRY MAY BE REQUIRED BEFORE MAKE INSTALL.**" ;\
	}

clean-update:
	{ \
	source $(conda info --base)/etc/profile.d/conda.sh ;\
	conda activate base ;\
	conda env remove -q -y --prefix $(PREFIX)neuroconda_build ;\
	echo "neuroconda clean-update completed, build environment removed." ;\
	}

clean-install:
	{ \
	source $(conda info --base)/etc/profile.d/conda.sh ;\
	conda activate base ;\
	conda env remove -q -y --prefix $(PREFIX)$(NEUROCONDA_VERSION) ;\
	echo "neuroconda clean-install completed, \
	neuroconda install at $(PREFIX)$(NEUROCONDA_VERSION) removed." ;\
	}
