# GNU Makefile for neuroconda. Commands:
# install (default target): create a new environment from neuroconda.yml
# update: create a new neuroconda.yml by building an environment from
# 	neuroconda_basepackages.yml and exporting.
# clean-update, clean-install: remove environments generated by update and install.
SHELL := /bin/bash
# make sure bash exceptions propagate to make
.SHELLFLAGS = -ec
NEUROCONDA_VERSION ?= neuroconda_1_5
NEUROCONDA_YML ?= neuroconda.yml

# default to first environment directory (tends to be user in centralized installs)
PREFIX ?= $(shell echo `conda info | grep "envs directories" | cut -d ":" -f 2`/)

NEUROCONDA_PATH = $(PREFIX)$(NEUROCONDA_VERSION)
NEUROCONDA_PATH_BUILD = $(PREFIX)neuroconda_build

install: clean-install
	{ \
	source $(conda info --base)/etc/profile.d/conda.sh ;\
	conda env create -f $(NEUROCONDA_YML) --prefix $(NEUROCONDA_PATH) ;\
	conda activate $(NEUROCONDA_PATH) ;\
	python -c "import cortex" ;\
	sed -i \
	's@build/bdist.linux-x86_64/wheel/pycortex-1.0.2.data/data@'$(NEUROCONDA_PATH)'@g' \
	~/.config/pycortex/options.cfg ;\
	jupyter serverextension enable --py jupyterlab_code_formatter ;\
	echo "neuroconda install completed at $(NEUROCONDA_PATH)." ;\
	}

update: clean-update
	{ \
	source $(conda info --base)/etc/profile.d/conda.sh ;\
	conda env create -f neuroconda_basepackages.yml --prefix $(NEUROCONDA_PATH_BUILD) ;\
	conda env export --prefix $(NEUROCONDA_PATH_BUILD) -f $(NEUROCONDA_YML) --no-builds ;\
	echo "neuroconda update completed, $(NEUROCONDA_YML) generated." ;\
	echo "**MANUAL EDITS TO DCM2BIDS PIP ENTRY MAY BE REQUIRED BEFORE MAKE INSTALL.**" ;\
	}

clean-update:
	{ \
	source $(conda info --base)/etc/profile.d/conda.sh ;\
	conda activate base ;\
	conda env remove -q -y --prefix $(NEUROCONDA_PATH_BUILD) ;\
	echo "neuroconda clean-update completed, build environment removed." ;\
	}

clean-install:
	{ \
	source $(conda info --base)/etc/profile.d/conda.sh ;\
	conda activate base ;\
	conda env remove -q -y --prefix $(NEUROCONDA_PATH) ;\
	echo "neuroconda clean-install completed, \
	neuroconda install at $(NEUROCONDA_PATH) removed." ;\
	}

test:
	{ \
	source $(conda info --base)/etc/profile.d/conda.sh ;\
	conda activate $(NEUROCONDA_PATH) ;\
	echo $(NEUROCONDA_PATH) ;\
	}
